services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: <%= ENV['PGPASSWORD'] || ''         %>
      POSTGRES_DB: intern_match_app_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["be", "full"]
    networks:
      - match-app
  be:
    build:
      context: ./back-end
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    # command: sleep infinity
    volumes:
      - ./back-end:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    profiles: ["be", "full"]
    networks:
      - match-app
    env_file:
      - .env
  fe:
    build:
      context: ./front-end
    command: sh -c "npm run dev"
    volumes:
      - ./front-end:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    profiles: ["fe", "full"]
    networks:
      - match-app
volumes:
  db_data:
  node_modules:

networks:
  match-app:
    external: true
    name: match-app