services:
  be:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes: 
      - .: /api
    ports:
      - "3001:3001"
    depends_on:
      - db
    
  db:
    image: postgres:17.5
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_DATABASE: intern_match_app_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres
volumes:
  db_data:
networks:
  default:
    external:
      name: front-end
